#include "tokens.hpp"

std::vector<std::string> tokenRegexps{"^and",
                                      "^array",
                                      "^begin",
                                      "^bool",
                                      "^call",
                                      "^case",
                                      "^char",
                                      "^constant",
                                      "^dim",
                                      "^do",
                                      "^else",
                                      "^end",
                                      "^false",
                                      "^for",
                                      "^if",
                                      "^input",
                                      "^integer",
                                      "^not",
                                      "^of",
                                      "^or",
                                      "^output",
                                      "^procedure",
                                      "^program",
                                      "^read",
                                      "^real",
                                      "^repeat",
                                      "^set",
                                      "^stop",
                                      "^then",
                                      "^to",
                                      "^true",
                                      "^until",
                                      "^var",
                                      "^while",
                                      "^write",
                                      "^[A-Za-z]\\w*",
                                      "^\\d+(?![A-Za-z])",
                                      "^'[^']*'",
                                      "^\\(",
                                      "^\\)",
                                      "^\\*",
                                      "^\\*/",
                                      "^\\+",
                                      "^,",
                                      "^-",
                                      "^\\.",
                                      "^\\.\\.",
                                      "^/",
                                      "^/\\*",
                                      "^:",
                                      "^:=",
                                      "^;",
                                      "^<",
                                      "^<=",
                                      "^<>",
                                      "^=",
                                      "^>",
                                      "^>=",
                                      "^\\[",
                                      "^\\]"};
std::string legalCharsRegexp = "^[\\w+-=\\[\\])'\\(*/,.:;><]";

Token::Token(Tokens type, const std::string& lexeme, const unsigned line,
             const unsigned col)
    : type(type), lexeme(lexeme), line(line), col(col) {}
